---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

images:
  base_image:
    name: 'quay.io/ansible/awx-ee:latest'

additional_build_files:
    - src: files/ansible.cfg
      dest: configs

additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip
   # - RUN useradd -m -u 1000 bvroot
   # - RUN passwd bvroot -p <vY8lia4fjtgWll4qNSpM>
   # - USER myuser
    - RUN dnf update -y
    - RUN dnf install openssl-devel bzip2-devel libffi-devel -y
    - RUN dnf group install "Development Tools" -y
    - RUN VERSION=3.13.3
    - ADD https://www.python.org/ftp/python/$VERSION/Python-$VERSION.tgz /tmp/Python-$VERSION.tgz
    - RUN tar -xzf /tmp/Python-$VERSION.tgz
    - RUN cd /tmp/Python-$VERSION.tgz/Python-$VERSION
    - RUN /tmp/Python-$VERSION.tgz/Python-$VERSION/./configure --enable-optimizations
    - RUN make altinstall
    - RUN /usr/local/bin/python3.13 -m pip install --upgrade pip
    - RUN pip3.13 install ansible --user

# RUN instructions within prepend & append are only here to see what happened when image is built
  prepend_final: |
    RUN whoami
    RUN cat /etc/os-release

  append_final:
    - RUN echo This is a post-install command!
    - RUN ls -la /etc
