---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

dependencies:
  ansible_core:
    package_pip: ansible-core==2.18
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

images:
  base_image:
    name: 'quay.io/ansible/awx-ee:latest'

additional_build_files:
    - src: files/ansible.cfg
      dest: configs

additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip

# RUN instructions within prepend & append are only here to see what happened when image is built
  prepend_final: |
    RUN whoami
    RUN cat /etc/os-release

  append_final:
    - RUN echo This is a post-install command!
    - RUN ls -la /etc
